# -*- coding: utf-8 -*-
"""Felmarginaler - Slutprojekt RFS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1McpgWTX5_ZaOjKE5UKHd9OwMNCwwjLc2
"""

from uncertainties import ufloat

# Parallaxvinkel, [m'']:
p_vinkel = ufloat(5.3389, 0.0236)

# Apparent Magnitud
mag_app = ufloat(12.8, 0.0005)

# λmax, [Å]:
λmax = ufloat(6500, 50)

# Relativ Flux:
relativF = ufloat(0.05, 0.001)

# Periodtid, [s]:
t = ufloat(122690, 0.000000001)

# Radiell hastighet, [m/s]:
v_max = ufloat(265.7, 8)

# Luminositet från parallaxvinkel och Apparent Magnitud

import numpy as np
from uncertainties.umath import log10


mag_abs_sol = 4.83
L_sol = 3.828 * (10 ** 26)

d = 1000 / p_vinkel
mag_abs = mag_app - (5 * log10(d / 10))
L = 10 ** (((mag_abs - mag_abs_sol) / -2.5)) * L_sol

print(f"Avstånd: {d} [pc]")
print(f"Absolut magnitud: {mag_abs}")
print(f"Luminositet: {L} [W]")

# Stjärnradie från λmax, och Luminositet (valfri)

import numpy as np
from uncertainties.umath import sqrt


λmax_m = λmax * (10 ** -10)
k = 2.898 * (10 ** -3)
boltz = 5.670374419 * (10 ** -8)

T = k / λmax_m
Rstar = sqrt( L / (4 * np.pi * boltz * (T ** 4)))

print(f"Temperatur: {T} [K]")
print(f"Stjärnradie: {Rstar} [m]")

# Stjärnmassa från Luminositet

m_sol = 1.9891 * (10 ** 30)
L_sol = 3.828 * (10 ** 26)


# Beräkna stjärnmassa
m_star = m_sol * ((L / L_sol) ** (2 / 7))

# Utskrift
print(f"Stjärnmassa: {m_star:.2e} kg")
print(f"Stjärnmassa i solmassor: {m_star / m_sol:.3f} M_sun")

# Planetmassa från Stjärnmassa, Periodtid och Radiell Hastighet


G = 6.6743 * (10 ** -11)

m_planet = (v_max * (m_star ** (2/3)) * (t ** (1/3))) / ((2 * np.pi * G) ** (1/3))

print(f"Planetmassa: {m_planet}")

# Volym från Relativ flux och Stjärnradie

import numpy as np
import matplotlib as plt


relativF = 0.05   # Relativ Flux (ΔF/F)


r_planet = Rstar * np.sqrt(relativF)
print(f"Planetär radie: {r_planet} [m]")

V_planet = (4/3) * np.pi * (r_planet ** 3)
print(f"Planetär volym: {V_planet} [m3]")

# Densitet från Massa och Volym

rho = m_planet / V_planet

print(f"Planetär desnitet: {rho} [kg/m3]")
print(f"Planetär desnitet: {rho/1000} [g/cm3]")

# Banmekanik för planethastighet och halva storaxeln

M_sum = m_star + m_planet

a = ((G * M_sum * t ** 2) / (4 * np.pi ** 2)) ** (1/3)

# Halva storaxeln antas vara ungefär lika stor som radien
# Alltså e = 1

v_bana = sqrt((G * M_sum) / a)

# Hastighet kontrollberäkning

s_omkrets = 2 * np.pi * a

v_kontroll = s_omkrets / t

print(f"Planetens kretshastighet: {v_kontroll} [m/s]")

print(f"Halva storaxeln: {a} [m]")
print(f"Halva storaxeln: {a / 149597871000} [AU]")
print(f"Planetens radialhastighet: {v_bana} [m/s]")

# Stjärndensitet bara för att

v_star = (4/3) * np.pi * (Rstar ** 3)
rho_s = m_star / v_star

print(f"Stellär Volym: {v_star} [m3]")
print(f"Stellär densitet: {rho_s} [kg/m3]")
print(f"Stellär desnitet: {rho_s/1000} [g/cm3]")

# Stjärntemperatur från en massa skit jag vet inte

T_planet = T * sqrt(Rstar / (2 * a))
print(f"Effektiv planettemperatur: {T_planet} K")

print(f"Avstånd: {d} [pc]")
print(f"Absolut magnitud: {mag_abs}")
print(f"Luminositet: {L} [W]")
print(f"Temperatur: {T} [K]")
print(f"Stjärnradie: {Rstar} [m]")
print(f"Stjärnmassa: {m_star:.2e} kg")
print(f"Stjärnmassa i solmassor: {m_star / m_sol:.3f} M_sun")
print(f"Planetmassa: {m_planet}")
print(f"Planetär radie: {r_planet} [m]")
print(f"Planetär volym: {V_planet} [m3]")
print(f"Planetär desnitet: {rho} [kg/m3]")
print(f"Planetär desnitet: {rho/1000} [g/cm3]")
print(f"Planetens kretshastighet: {v_kontroll} [m/s]")
print(f"Halva storaxeln: {a} [m]")
print(f"Halva storaxeln: {a / 149597871000} [AU]")
print(f"Planetens radialhastighet: {v_bana} [m/s]")
print(f"Stellär Volym: {v_star} [m3]")
print(f"Stellär densitet: {rho_s} [kg/m3]")
print(f"Stellär desnitet: {rho_s/1000} [g/cm3]")
print(f"Effektiv planettemperatur: {T_planet} K")